00.baekjoon/027-13305.ts
00.baekjoon/028-1931.ts
02.programmers-Lv1/001-K번째수.ts
02.programmers-Lv1/002-체육복.ts
03.programmers-Lv2/001-가장큰수.ts
03.programmers-Lv2/002-H-Index.ts

@f-lab-jake 
멘토님, 새로운 문제 풀이 6개 PR 올립니다!

[23.12.14] 알고리즘 문제 풀이

---

00.baekjoon/029-2512.ts
00.baekjoon/030-2805.ts
00.baekjoon/031-1654.ts
00.baekjoon/032-1931.ts
00.baekjoon/033-10816.ts
00.baekjoon/034-2720.ts
00.baekjoon/035-10162.ts
00.baekjoon/036-5585.ts
01.programmers-Lv0/036.ts
01.programmers-Lv0/037.ts
01.programmers-Lv0/038.ts
01.programmers-Lv0/039.ts
01.programmers-Lv0/040.ts
01.programmers-Lv0/041-배열만들기5.ts
01.programmers-Lv0/042-문자열만들기.ts
01.programmers-Lv0/043-문자열뒤n글자.ts
01.programmers-Lv0/044-접미사배열.ts
01.programmers-Lv0/045-접미사.ts
03.programmers-Lv2/001-조이스틱.ts
03.programmers-Lv2/002-큰수만들기.ts
templates/bs.ts

@f-lab-jake 
멘토님 새로운 문제 풀이 PR 올립니다!

[23.12.21] 알고리즘 문제 풀이

---

01.programmers-Lv0/046-문자열앞n글자.ts
01.programmers-Lv0/047-접두사.ts
01.programmers-Lv0/048-문자열뒤집기.ts
01.programmers-Lv0/049-세로읽기.ts
01.programmers-Lv0/050-qrCode.ts
02.programmers-Lv1/003-완주하지못한선수.ts
02.programmers-Lv1/004-폰켓몬.ts
03.programmers-Lv2/003-전화번호목록.ts
03.programmers-Lv2/004-의상.ts

[23.12.25] 알고리즘 문제 풀이

---

01.programmers-Lv0/051-문자개수세기.ts
01.programmers-Lv0/052-배열만들기.ts
01.programmers-Lv0/053-글자지우기.ts
02.programmers-Lv1/003-달리기경주.ts
02.programmers-Lv1/004-추억점수.ts
04.programmers-Lv3/001-베스트앨범.ts
package-lock.json
package.json

@f-lab-jake 
멘토님 새로운 문제 풀이 PR 드립니다!

[23.12.29] 알고리즘 문제 풀이

---

01.programmers-Lv0/051-문자개수세기.ts
01.programmers-Lv0/052-배열만들기.ts
01.programmers-Lv0/053-글자지우기.ts
01.programmers-Lv0/054-카운트다운.ts
01.programmers-Lv0/055-가까운1찾기.ts
02.programmers-Lv1/003-달리기경주.ts
02.programmers-Lv1/004-추억점수.ts
02.programmers-Lv1/005-공원산책.ts
02.programmers-Lv1/006-같은숫자는싫어.ts
03.programmers-Lv2/003-기능개발.ts
03.programmers-Lv2/004-올바른괄호.ts
03.programmers-Lv2/005-프로세스.ts
04.programmers-Lv3/001-베스트앨범.ts
package-lock.json
package.json

@f-lab-jake 
멘토님 새로운 문제 풀이 PR 드립니다.
이전 PR 2개에도 수정사항이 있는데 함께 봐주시면 감사드리겠습니다. 🙇🏻‍♀️

[24.01.05] 알고리즘 문제 풀이

---

02.programmers-Lv1/007-문자열정수로바꾸기.ts
02.programmers-Lv1/008-나머지가1이되는수.ts
02.programmers-Lv1/009-짝수와홀수.ts
02.programmers-Lv1/010-평균구하기.ts
02.programmers-Lv1/011-약수의합.ts

@f-lab-jake 
멘토님 새로운 문제 풀이 PR 올립니다.
- 프로그래머스 Lv.1 5문제

[24.01.12] 알고리즘 문제 풀이

---

02.programmers-Lv1/015-자연수뒤집기.ts
02.programmers-Lv1/016-정수제곱근판별.ts
02.programmers-Lv1/017-정수내림차순배치.ts
03.programmers-Lv2/007-최솟값만들기.ts
03.programmers-Lv2/008-이진변환반복하기.ts

@f-lab-jake 
멘토님 새로운 문제 풀이 PR 올립니다.

[24.01.14] 알고리즘 문제 풀이

---

02.programmers-Lv1/021-콜라츠추측.ts
02.programmers-Lv1/022-김서방찾기.ts
02.programmers-Lv1/023-나누어떨어지는숫자배열.ts
03.programmers-Lv2/011-피보나치수.ts
03.programmers-Lv2/012-짝지어제거하기.ts

[24.01.16] 알고리즘 문제 풀이

---

02.programmers-Lv1/024-없는숫자더하기.ts
02.programmers-Lv1/025-핸드폰번호가리기.ts
02.programmers-Lv1/026-제일작은수제거.ts
03.programmers-Lv2/013-카펫.ts
03.programmers-Lv2/014-영어끝말잇기.ts

[24.01.17] 알고리즘 문제 풀이

---

02.programmers-Lv1/024-내적.ts
02.programmers-Lv1/025-가운데글자가져오기.ts
02.programmers-Lv1/026-수박수박수.ts
03.programmers-Lv2/013-점프와순간이동.ts
03.programmers-Lv2/014-구명보트.ts

[24.01.18] 알고리즘 문제 풀이

---

.eslintrc.js
02.programmers-Lv1/030-약수의개수와덧셈.ts
02.programmers-Lv1/031-문자열내림차순배치.ts
02.programmers-Lv1/032-부족한금액.ts
03.programmers-Lv2/017-예상대진표.ts
03.programmers-Lv2/018-N개의최소공배수.ts

@f-lab-jake 
- 최대공배수를 구하는 함수를 알아두면 좋을 것 같아 참고하여 적용했습니다.

[24.01.19] 알고리즘 문제 풀이

---

02.programmers-Lv1/033-문자열다루기.ts
02.programmers-Lv1/034-행렬의덧셈.ts
02.programmers-Lv1/035-직사각형별찍기.ts
03.programmers-Lv2/019-멀리뛰기.ts
03.programmers-Lv2/020-귤고르기.ts

[24.01.20] 알고리즘 문제 풀이

---

02.programmers-Lv1/036-최대공약수와최대공배수.ts
02.programmers-Lv1/037-3진법뒤집기.ts
02.programmers-Lv1/038-예산.ts
03.programmers-Lv2/021-연속부분수열합의개수.ts
03.programmers-Lv2/022-괄호회전하기.ts

[24.01.21] 알고리즘 문제 풀이

---

02.programmers-Lv1/039-이상한문자만들기.ts
02.programmers-Lv1/040-크기가작은부분문자열.ts
02.programmers-Lv1/041-삼총사.ts
03.programmers-Lv2/023-할인행사.ts
03.programmers-Lv2/024-n^2배열자르기.ts

@f-lab-jake 
멘토님, 새로운 문제 PR 올립니다.

[24.01.24] 알고리즘 문제 풀이

---

02.programmers-Lv1/042-최소직사각형.ts
02.programmers-Lv1/043-시저암호.ts
02.programmers-Lv1/044-가장가까운같은글자.ts
03.programmers-Lv2/025-행렬의곱셈.ts
03.programmers-Lv2/026-캐시.ts

[24.01.25] 알고리즘 문제 풀이

---

.prettierrc
00.baekjoon/038-1012.ts
02.programmers-Lv1/048-실패율.ts
03.programmers-Lv2/028-최소피로도.ts

[24.02.07] 알고리즘 문제 풀이

---

00.baekjoon/BFS/002-2644.ts
00.baekjoon/BFS/003-7562.ts
00.baekjoon/BFS/004-2468.ts
00.baekjoon/BFS/005-2583.ts

@f-lab-jake 
지난 주 PR 개선사항도 함께 봐주시면 감사드리겠습니다.🤗

[24.03.03] 알고리즘 문제 풀이

---

00.baekjoon/구현/001-2979.ts
00.baekjoon/완전탐색/001-2231.ts
00.baekjoon/완전탐색/002-2309.ts
00.baekjoon/완전탐색/003-10448.ts
00.baekjoon/완전탐색/004-1436.ts
00.baekjoon/완전탐색/005-1018.ts
00.baekjoon/완전탐색/006-17484.ts
03.programmers-Lv2/029-소수찾기.ts

@f-lab-jake 
멘토님, 알고리즘 문제 풀이 PR 올립니다.

[24.03.19] 알고리즘 문제 풀이

---

04.programmers-Lv3/002-네트워크.ts
LeetCode/207-CourseSchedule.ts

@f-lab-jake 
멘토님, 알고리즘 문제 풀이 PR 올립니다.

[24.04.06] 알고리즘 문제 풀이

---

LeetCode/210-CourseSchedule2.ts
LeetCode/997-FindtheTownJudge.ts

@f-lab-jake 
- `Course Schedule 2` 문제는 직전에 푼 문제와 비슷한 유형이지만 연습겸 이어서 풀어보았습니다.

[24.04.09] 알고리즘 문제 풀이

---

00.baekjoon/DFS&BFS/006-2178.ts
00.baekjoon/DFS&BFS/007-1388(S4).ts
00.baekjoon/DFS&BFS/008-16173(S4).ts

[24.02.27] 알고리즘 문제 풀이

---

00.baekjoon/029-2512.ts
00.baekjoon/030-2805.ts
00.baekjoon/031-1654.ts
03.programmers-Lv2/001-조이스틱.ts
03.programmers-Lv2/002-큰수만들기.ts

@f-lab-jake 
멘토님, 알고리즘 5문제 풀이 PR 올립니다.
- 조이스틱 문제는 이해가 잘 되지 않습니다. 특히 `minMove` 를 구하는 부분이 와닿지 않습니다.
우선 함께 올리고 계속 고민해보도록 하겠습니다.

[23.12.16] 알고리즘 문제 풀이

---

02.programmers-Lv1/005-바탕화면정리.ts
02.programmers-Lv1/006-덧칠하기.ts
03.programmers-Lv2/006-다리를지나는트럭.ts
templates/queue.ts

@f-lab-jake 
멘토님, 새로운 문제 풀이와 큐 구현 PR 올립니다.
`[006-다리를지나는트럭.ts]`은 잠시 넘겨주세요. 해당 문제는 조금만 더 고민해보고 다시 올리겠습니다.

[24.01.09] 알고리즘 문제 풀이

---

00.baekjoon/037-2606.ts
02.programmers-Lv1/045-숫자문자열과영단어.ts
02.programmers-Lv1/046-소수찾기.ts
02.programmers-Lv1/047-푸드파이터대회.ts
03.programmers-Lv2/027-튜플.ts

[24.02.03] 알고리즘 문제 풀이
